#!/usr/bin/env bash

firefox_path="/opt/firefox"
lang=$(locale | grep LANG= | cut -d= -f2 | cut -d "." -f1 | tr '_' '-')
download_url="https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=$lang"
icon_url="https://design.firefox.com/product-identity/firefox/firefox/firefox-logo.png"
firefox_version=$(curl -s "$download_url" | cut -d"/" -f 7)

if [ ! -f "$firefox_path/$firefox_version/firefox" ]; then
    mkdir -p "$firefox_path"
    if [ ! -d "$firefox_path" ]; then
        echo "- Error. $firefox_path doesn't exist!"
    else
        echo "- Downloading Firefox $firefox_version..."
        wget "$download_url" -q -O "/tmp/firefox.tar.bz2" > /dev/null
        echo "- Extracting Firefox $firefox_version..."
        tar xf /tmp/firefox.tar.bz2 -C $firefox_path/ 
        echo "- Moving Firefox $firefox_version..."
        mv "$firefox_path/firefox" "$firefox_path/$firefox_version"
        if [ ! -f "$firefox_path/$firefox_version/firefox" ]; then
            echo "- Error!"
        else
            [ -f "$firefox_path/next_version_remove" ] && rm $firefox_path/$(cat "$firefox_path/next_version_remove")    
            [ -f "$firefox_path/version" ] && mv "$firefox_path/version" "$firefox_path/next_version_remove"
            echo "- Creating links..."
            ln -f -s -r "$firefox_path/$firefox_version" "$firefox_path/current"
            ln -f -s "$firefox_path/$firefox_version/firefox" "/usr/bin/firefox"
            echo "- Downloading icon..."
            wget "$icon_url" -q -O "$firefox_path/firefox.png" > /dev/null
            echo "- Cleaning..."
            rm "/tmp/firefox.tar.bz2" 
            echo "$firefox_version" > "$firefox_path/version"
            echo "- Firefox $firefox_version: OK."
        fi
    fi
fi

